# Generated by Django 5.2.7 on 2025-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zhouyi_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortunerecord",
            name="ai_interpretation",
            field=models.TextField(blank=True, verbose_name="AI解释"),
        ),
        migrations.AddField(
            model_name="fortunerecord",
            name="sentiment_analysis",
            field=models.JSONField(blank=True, null=True, verbose_name="情感分析"),
        ),
        migrations.AddField(
            model_name="fortunerecord",
            name="similar_cases",
            field=models.JSONField(blank=True, null=True, verbose_name="相似案例"),
        ),
        migrations.AddField(
            model_name="fortunerecord",
            name="trend_prediction",
            field=models.JSONField(blank=True, null=True, verbose_name="趋势预测"),
        ),
        migrations.AddIndex(
            model_name="fortunerecord",
            index=models.Index(
                fields=["hexagram_name"], name="zhouyi_app__hexagra_fd6900_idx"
            ),
        ),
    ]
