# Generated by Django 5.2.7 on 2025-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zhouyi_app", "0002_fortunerecord_ai_interpretation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortunerecord",
            name="ai_thinking",
            field=models.TextField(blank=True, verbose_name="AI思考过程"),
        ),
        migrations.AddField(
            model_name="fortunerecord",
            name="interpretation_source",
            field=models.CharField(
                default="rule_based", max_length=20, verbose_name="解释来源"
            ),
        ),
    ]
