# Generated by Django 5.2.7 on 2025-11-02 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zhouyi_app", "0003_fortunerecord_ai_thinking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fortunerecord",
            name="ai_thinking",
        ),
        migrations.RemoveField(
            model_name="fortunerecord",
            name="interpretation_source",
        ),
    ]
